# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5ea45ba934b16d9a5913bdefbc81066c2d63290699ced23b45faeace9df2ab30dacc42c0665ebb0bafda1b3fa6f9cd53cb5bdae862bf3aadabcb208f21f49ee

test:
  secret_key_base: d5c595812bc8d8db3cab7258c104aff242dbd4832ac8225520cf141c8101e4b1d001123a60915387bd4b65eb39bf5328658f98059d3f4a848a48417a1f6b1c1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
